//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalFinalEntities : DbContext
    {
        public HospitalFinalEntities()
            : base("name=HospitalFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutPhoto> AboutPhotoes { get; set; }
        public virtual DbSet<Appoinment> Appoinments { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<DayTime> DayTimes { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<OpeningHour> OpeningHours { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<AboutClinic> AboutClinics { get; set; }
    }
}
